### PR TITLE
Remove unused derived instances

### PR DESCRIPTION
**Pull request by moodmosaic**
Makes the code easier to read on a plain text editor (GitHub, Sublime Text with no add-ins, etcetera). It passes all automated tests.

---

```
$ stack test
UserManagement-0.1.0.0: test (suite: UserManagement-test)

Properties:
  Users successfully connect: [OK, passed 100 tests]
  Users don't connect when user doesn't exist: [OK, passed 100 tests]
  Users don't connect when other user doesn't exist: [OK, passed 100 tests]
  Users don't connect when user Id is invalid: [OK, passed 100 tests]
  Users don't connect when other user Id is invalid: [OK, passed 100 tests]

         Properties  Total
 Passed  5           5
 Failed  0           0
 Total   5           5

UserManagement-0.1.0.0: Test suite UserManagement-test passed

Nikos@WIN-NJGAFM9CA3G MINGW64 ~/tmp/ploeh/UserManagement/Haskell
  (topic/housekeeping-haskell-derived-instances)
```

### CODE REVIEW

**Comment by ploeh** [comment]
I'm not sure I understand how this is an improvement. How does this make the code easier to read in normal text editors?

**Comment by moodmosaic** [comment]
The way I (but also @jystic and others) work with Haskell is to *just* use a code editor (Vim, Sublime Text, etc) for syntax highlighting only (and do the rest from inside GHCi).

Perhaps with some smart extension on Visual Studio Code or Atom, one can easily figure out where those derived instances are used.

However, when I was reading this piece of source code, I was wondering why and where those derived instance are used. And it turns out they aren't actually used anywhere(?) So why keep them around?

**Comment by ploeh** [comment]
This is completely subjective, but I disagree that the presence of entirely benign type classes like `Eq` and `Show` decreases readability, text editor or not.

They may not be used right now, but if one needs them later, it'd be annoying to have to go and add them.

`Show`, particularly, is often useful when you're playing around with types in GHCi, so it'd be extra annoying if I'd have to go and add that every time I want to experiment with types in that way.

I'm ready to accept that the `Functor` instance isn't necessary, so perhaps one could remove that, but I don't find it terribly important.

Thank you for the pull request, but for the above reasons, I'll decline it.

**Comment by moodmosaic** [comment]
>it'd be annoying to have to go and add them [..] often useful when you're playing around with types in GHCi

If that's the reason you didn't specify `ghc-options` in the `library` section of the `.cabal` file, fair enough. I would at least specify `-Wall` and add/remove warnings inside the `.ghci` file (local, or global one).

```diff
$ git diff
diff --git a/Haskell/UserManagement.cabal b/Haskell/UserManagement.cabal
index 2787cb4..b89e528 100644
--- a/Haskell/UserManagement.cabal
+++ b/Haskell/UserManagement.cabal
@@ -14,6 +14,8 @@ library
   build-depends:       base >= 4.7 && < 5
                      , transformers
   default-language:    Haskell2010
+  ghc-options:         -Wall

 test-suite UserManagement-test
   type:                exitcode-stdio-1.0
```

```
$ stack ghci
...

\UserManagement\Haskell\src\UserManagement.hs:5:1: warning: [-Wunused-imports]
    The import of `Data.Either' is redundant
      except perhaps to import instances from `Data.Either'
    To import instances alone, use: import Data.Either()
  |
5 | import Data.Either
  | ^^^^^^^^^^^^^^^^^^

\UserManagement\Haskell\src\UserManagement.hs:32:28: warning: [-Wname-shadowing]
    This binding for `userId' shadows the existing binding
      defined at C:\Snapshot\tmp\ploeh\UserManagement\Haskell\src\UserManagement.hs:19:20
   |
32 | post lookupUser updateUser userId otherUserId = do
   |                            ^^^^^^
Ok, one module loaded.
```

With `-Weverything`

```diff
diff --git a/Haskell/UserManagement.cabal b/Haskell/UserManagement.cabal
index 2787cb4..b89e528 100644
--- a/Haskell/UserManagement.cabal
+++ b/Haskell/UserManagement.cabal
@@ -14,6 +14,8 @@ library
   build-depends:       base >= 4.7 && < 5
                      , transformers
   default-language:    Haskell2010
+  ghc-options:         -Weverything

 test-suite UserManagement-test
   type:                exitcode-stdio-1.0
```

```
$ stack ghci
...

\UserManagement\Haskell\src\UserManagement.hs, interpreted )

\UserManagement\Haskell\src\UserManagement.hs:1:1: warning: [-Wimplicit-prelude]
    Module `Prelude' implicitly imported
  |
1 | {-# LANGUAGE DeriveFunctor #-}
  | ^

\UserManagement\Haskell\src\UserManagement.hs:6:1: warning: [-Wunused-imports]
    The import of `Data.Either' is redundant
      except perhaps to import instances from `Data.Either'
    To import instances alone, use: import Data.Either()
  |
6 | import Data.Either
  | ^^^^^^^^^^^^^^^^^^

\UserManagement\Haskell\src\UserManagement.hs:33:28: warning: [-Wname-shadowing]
    This binding for `userId' shadows the existing binding
      defined at C:\Snapshot\tmp\ploeh\UserManagement\Haskell\src\UserManagement.hs:20:20
   |
33 | post lookupUser updateUser userId otherUserId = do
   |                            ^^^^^^
Ok, one module loaded.
```

By default, you get a standard set of [GHC warnings](https://downloads.haskell.org/~ghc/master/users-guide/using-warnings.html), that's why GHCi doesn't complain as-is right now...

**Comment by moodmosaic** [comment]
>it'd be annoying to have to go and add them [..] often useful when you're playing around with types in GHCi

If that's the reason you didn't specify `ghc-options` in the `library` section of the `.cabal` file, fair enough. I would at least specify `-Wall` and add/remove warnings inside the `.ghci` file (local, or global one).

```diff
$ git diff
diff --git a/Haskell/UserManagement.cabal b/Haskell/UserManagement.cabal
index 2787cb4..b89e528 100644
--- a/Haskell/UserManagement.cabal
+++ b/Haskell/UserManagement.cabal
@@ -14,6 +14,8 @@ library
   build-depends:       base >= 4.7 && < 5
                      , transformers
   default-language:    Haskell2010
+  ghc-options:         -Wall

 test-suite UserManagement-test
   type:                exitcode-stdio-1.0
```

```
$ stack ghci
...

\UserManagement\Haskell\src\UserManagement.hs:5:1: warning: [-Wunused-imports]
    The import of `Data.Either' is redundant
      except perhaps to import instances from `Data.Either'
    To import instances alone, use: import Data.Either()
  |
5 | import Data.Either
  | ^^^^^^^^^^^^^^^^^^

\UserManagement\Haskell\src\UserManagement.hs:32:28: warning: [-Wname-shadowing]
    This binding for `userId' shadows the existing binding
      defined at \UserManagement\Haskell\src\UserManagement.hs:19:20
   |
32 | post lookupUser updateUser userId otherUserId = do
   |                            ^^^^^^
Ok, one module loaded.
```

With `-Weverything`

```diff
diff --git a/Haskell/UserManagement.cabal b/Haskell/UserManagement.cabal
index 2787cb4..b89e528 100644
--- a/Haskell/UserManagement.cabal
+++ b/Haskell/UserManagement.cabal
@@ -14,6 +14,8 @@ library
   build-depends:       base >= 4.7 && < 5
                      , transformers
   default-language:    Haskell2010
+  ghc-options:         -Weverything

 test-suite UserManagement-test
   type:                exitcode-stdio-1.0
```

```
$ stack ghci
...

\UserManagement\Haskell\src\UserManagement.hs, interpreted )

\UserManagement\Haskell\src\UserManagement.hs:1:1: warning: [-Wimplicit-prelude]
    Module `Prelude' implicitly imported
  |
1 | {-# LANGUAGE DeriveFunctor #-}
  | ^

\UserManagement\Haskell\src\UserManagement.hs:6:1: warning: [-Wunused-imports]
    The import of `Data.Either' is redundant
      except perhaps to import instances from `Data.Either'
    To import instances alone, use: import Data.Either()
  |
6 | import Data.Either
  | ^^^^^^^^^^^^^^^^^^

\UserManagement\Haskell\src\UserManagement.hs:33:28: warning: [-Wname-shadowing]
    This binding for `userId' shadows the existing binding
      defined at \UserManagement\Haskell\src\UserManagement.hs:20:20
   |
33 | post lookupUser updateUser userId otherUserId = do
   |                            ^^^^^^
Ok, one module loaded.
```

By default, you get a standard set of [GHC warnings](https://downloads.haskell.org/~ghc/master/users-guide/using-warnings.html), that's why GHCi doesn't complain as-is right now...

**Pull request closed without merging**
